// 1.hello-world/3.read-and-parse-drivers-license-vue3/src/components/ImgParser.vue
<template>
  <div class="ImgDecode"><input type="file" @change="decodeImg"/></div>
</template>

<script>
import { onBeforeUnmount, ref } from "vue";
import { BarcodeReader, EnumBarcodeFormat } from 'dynamsoft-javascript-barcode';
import { CodeParser, EnumCodeFormat } from 'shen-dynamsoft-code-parser';

export default {
  setup() {
    const pReader = ref(null);
    const pParser = ref(null);

    const decodeImg = async (e) => {
      try {
        const reader = await (pReader.value = pReader.value || BarcodeReader.createInstance());
        const settings = await reader.getRuntimeSettings();
        settings.barcodeFormatIds = 0;
        settings.barcodeFormatIds_2 = 0;
        settings.barcodeFormatIds |= EnumBarcodeFormat.BF_PDF417;
        settings.barcodeFormatIds |= EnumBarcodeFormat.BF_QR_CODE;
        await reader.updateRuntimeSettings(settings);

        const parser = await (pParser.value = pParser.value || CodeParser.createInstance());
        await parser.setCodeFormat(EnumCodeFormat.CF_AUTO);

        let results = await reader.decode(e.target.files[0]);

        for(let i=0;i<results.length;i++) {
          const info = await parser.parseData(results[i].barcodeBytes);
          alert(JSON.stringify(info));
          console.log(info);
        }

        if(!results.length){ alert('No barcode found'); }
      } catch(ex) {
        alert(ex);
      }
      e.target.value = '';
    }
    onBeforeUnmount(async () => {
      if (pReader.value) {
        (await pReader.value).destroyContext();
        (await pParser.value).destroyContext();
        console.log('ImgParser Component Unmount');
      }
    })

    return {
      decodeImg
    }
  }
}
</script>

<style scoped>
  .ImgDecode {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: 90%;
    border: 1px solid black
  }
</style>

// 1.hello-world/2.read-and-parse-drivers-license-react/src/components/ImgParser/ImgParser.js
import React, { Component } from 'react'
import { BarcodeReader, EnumBarcodeFormat } from "dynamsoft-javascript-barcode";
import { CodeParser, EnumCodeFormat } from 'shen-dynamsoft-code-parser';
import './ImgParser.css'

export default class ImgDecode extends Component {
  constructor(props) {
    super(props);
    this.pReader = null;
    this.pParser = null;
  }

  decodeImg = async (e) => {
    try {
      const reader = await (this.pReader = this.pReader || BarcodeReader.createInstance());
      const settings = await reader.getRuntimeSettings();
      settings.barcodeFormatIds = 0;
      settings.barcodeFormatIds_2 = 0;
      settings.barcodeFormatIds |= EnumBarcodeFormat.BF_PDF417;
      settings.barcodeFormatIds |= EnumBarcodeFormat.BF_QR_CODE;
      await reader.updateRuntimeSettings(settings);

      const parser = await (this.pParser = this.pParser || CodeParser.createInstance());
      await parser.setCodeFormat(EnumCodeFormat.CF_AUTO);

      let results = await reader.decode(e.target.files[0]);

      for(let i=0;i<results.length;i++) {
        const info = await parser.parseData(results[i].barcodeBytes);
        alert(JSON.stringify(info));
        console.log(info);
      }

      if(!results.length){ alert('No barcode found'); }
    } catch(ex) {
      alert(ex);
    }
    e.target.value = '';
  }

  async componentWillUnmount() {
    if (this.pReader) {
      (await this.pReader).destroyContext();
      (await this.pParser).destroyContext();
      console.log('ImgParser Component Unmount');
    }
  }

  render() {
    return (
      <div className="ImgDecode"><input type="file" onChange={this.decodeImg}/></div>
    )
  }
}
