// 1.hello-world/2.read-and-parse-drivers-license-react/src/components/HelloWorld/HelloWorld.js
import './HelloWorld.css';
import reactLogo from '../../logo.svg';
import "../../dbr"; // import side effects. The license, engineResourcePath, so on.
import "../../dcp"; // import side effects. The license, engineResourcePath, so on.
import { BarcodeReader } from "dynamsoft-javascript-barcode";
import { CodeParser } from "shen-dynamsoft-code-parser";
import React from 'react';
import VideoParser from '../VideoParser/VideoParser';
import ImgParser from '../ImgParser/ImgParser';

class HelloWorld extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            bShowScanner: true,
            bShowImgDecode: false
        };
    }
    async componentDidMount() {
        try {
            await BarcodeReader.loadWasm();
            await CodeParser.loadWasm();
        } catch (ex) {
            alert(ex);
            throw ex;
        }
    }

    showScanner = () => {
        this.setState({
            bShowScanner: true,
            bShowImgDecode: false
        });
    }

    showImgDecode = () => {
        this.setState({
            bShowScanner: false,
            bShowImgDecode: true
        });
    }
    
    render() {
        return (
            <div className="helloWorld">
                <h1>Hello World for React<img src={reactLogo} className="App-logo" alt="logo" /></h1>
                <div className="btn-group">
                    <button style={{marginRight: '10px', backgroundColor: this.state.bShowScanner ? 'rgb(255,174,55)' : 'white'}} onClick={this.showScanner}>Video Decode</button>
                    <button style={{backgroundColor: this.state.bShowImgDecode ? 'rgb(255,174,55)' : 'white'}} onClick={this.showImgDecode}>Image Decode</button>
                </div>
                <div className="container">
                    {this.state.bShowScanner ? (<VideoParser></VideoParser>) : ""}
                    {this.state.bShowImgDecode ? (<ImgParser></ImgParser>) : ""}
                </div>
            </div>
        );
    }
}
export default HelloWorld;

// 1.hello-world/3.read-and-parse-drivers-license-vue3/src/components/HelloWorld.vue
<template>
  <div className="helloWorld">
    <h1>Hello World for Vue 3 <img class="applogo" alt="Vue logo" src="../assets/logo.png" /></h1>
    <div class="btn-group">
        <button :style="{marginRight: '10px', backgroundColor: bShowScanner ? 'rgb(255,174,55)' : 'white'}" @click="showScanner">Video Decode</button>
        <button :style="{backgroundColor: bShowImgDecode ? 'rgb(255,174,55)' : 'white'}"  @click="showImgDecode">Image Decode</button>
    </div>
    <div class="container">
      <VideoParser v-if="bShowScanner"></VideoParser>
      <ImgParser v-if="bShowImgDecode"></ImgParser>
    </div>
  </div>
</template>

<script>
import "../dbr"; // import side effects. The license, engineResourcePath, so on.
import "../dcp"; // import side effects. The license, engineResourcePath, so on.
import { BarcodeScanner } from 'dynamsoft-javascript-barcode';
import { CodeParser } from 'shen-dynamsoft-code-parser';
import VideoParser from "./VideoParser";
import ImgParser from './ImgParser'
import { ref, onMounted } from "vue";

export default {
  name: "HelloWorld",
  setup() {
    const bShowScanner = ref(true);
    const bShowImgDecode = ref(false)
    onMounted(async () => {
      try {
        //Load the library on page load to speed things up.
        await BarcodeScanner.loadWasm();
        await CodeParser.loadWasm();
      } catch (ex) {
        alert(ex);
      }
    });
    const showScanner = () => {
      bShowScanner.value = true;
      bShowImgDecode.value = false;
    };
    const showImgDecode = () => {
      bShowScanner.value = false;
      bShowImgDecode.value = true;
    }
    return {
      bShowScanner,
      showScanner,
      showImgDecode,
      bShowImgDecode
    };
  },
  components: {
    VideoParser, ImgParser
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
button {
  font-size: 1.5rem;
  margin-bottom: 2vh;
  border: 1px solid black;
}
.container {
  margin: 2vmin auto;
  text-align: center;
  font-size: medium;
  /* height: 40vh; */
  width: 80vw;
}
.applogo {
  height: 25px;
}
.helloWorld {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  width: 100%;
  height: 100%;
  color: #455a64;
}
h1 {
  font-size: 1.5em;
}
</style>
